TRUNCATE TABLE guardias_guardia_ausencias RESTART IDENTITY CASCADE;
TRUNCATE TABLE guardias_guardia RESTART IDENTITY CASCADE;
TRUNCATE TABLE guardias_listaguardias RESTART IDENTITY CASCADE;
TRUNCATE TABLE guardias_centro RESTART IDENTITY CASCADE;
TRUNCATE TABLE guardias_organizacion RESTART IDENTITY CASCADE;
TRUNCATE TABLE guardias_vacacionesanuales RESTART IDENTITY CASCADE;
TRUNCATE TABLE users_user RESTART IDENTITY CASCADE;
